NoResolverConfiguration error fixed
while doing passive recon i encountered the following error which is fixed now:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/dns/resolver.py", line 992, in read_resolv_conf
    cm: contextlib.AbstractContextManager = open(f)
                                            ^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'apple.com'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/tools/Gsec/gsec.py", line 189, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/root/tools/Gsec/gsec.py", line 124, in main
    await asyncio.gather(
  File "/root/tools/Gsec/utils/passive_recon.py", line 34, in dns_info
    mail_exchange = dns.resolver.Resolver(domain, "MX")
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/dns/resolver.py", line 944, in __init__
    self.read_resolv_conf(filename)
  File "/usr/local/lib/python3.11/dist-packages/dns/resolver.py", line 995, in read_resolv_conf
    raise NoResolverConfiguration(f"cannot open {f}")
dns.resolver.NoResolverConfiguration: cannot open apple.com
```